### ISSUE TITLE
Latest Version of gorm.io/gorm Not Detected Correctly

### ISSUE THREAD

**Issue by kbukum** [filllabs/dependi#1]
**Describe the bug**
I am using the latest version of the gorm.io/gorm library (v1.25.10), but it is showing v1.25.9 as not installed as the latest version. Please see the version information here: https://pkg.go.dev/gorm.io/gorm@v1.25.10?tab=versions

**To Reproduce**
1. Install gorm.io/gorm library version v1.25.10.
2. Use the Dependi plugin to check the version status.
3. Notice that it incorrectly shows v1.25.9 as not the latest installed version.

**Expected behavior**
The version check should recognize v1.25.10 as the latest installed version. https://pkg.go.dev/gorm.io/gorm@v1.25.10?tab=versions

**Screenshots**
<img width="361" alt="Screenshot 2024-07-02 at 1 07 36 AM" src="https://github.com/filllabs/dependi/assets/915074/dca6f894-0819-44a0-a864-88173f5b0c21">

<img width="412" alt="Screenshot 2024-07-02 at 12 57 53 AM" src="https://github.com/filllabs/dependi/assets/915074/73eef986-34eb-46ba-b9d0-d2b0417c67ff">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 23.5.0

**Additional context**
I am using Visual Studio Code with the following setup:

Version: 1.90.1 (Universal)
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

**Comment by kbukum** [comment]
Also I can see in the list, it is not showing the latest version. I believe this may be the issue. The list is not up-to-date

<img width="831" alt="Screenshot 2024-07-02 at 2 36 24 AM" src="https://github.com/filllabs/dependi/assets/915074/75f2b1db-89a6-4c6e-8dd7-87bbb54bb0ac">

**Comment by MOzanGul** [comment]
Hi @kbukum, we have fixed this issue on our newer versions.
We'd be really happy if you could review Dependi, here is our [marketplace page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
