### ISSUE TITLE
Including the same crate for two distinct targets in my project displays two `√√` symbols on a single line.

### ISSUE THREAD

**Issue by xb284524239** [filllabs/dependi#100]
**Describe the bug**
Including the same crate for two distinct targets in my project displays two `√√` symbols on a single line.

**To Reproduce**
```
# Cargo.toml, for example:

[package]
name = "test007"
version = "0.1.0"
edition = "2021"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
slint = { version = "1.7",  default-features = false, features = ["compat-1-2", "backend-winit", "renderer-skia"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
slint = { version = "1.7", default-features = false, features = ["compat-1-2", "backend-winit", "renderer-femtovg"] }
```

**Expected behavior**
The symbol `√` appears following each instance.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: lasted

**Screenshots**
![aaa](https://github.com/user-attachments/assets/3453aab3-01ce-4e38-8aec-b3dd74612b86)

**Comment by MOzanGul** [comment]
Hi @xb284524239, we have fixed this issue in our newest version 0.7.8. 
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
