### ISSUE TITLE
Issue with go.mod Format in Dependi Plugin

### ISSUE THREAD

**Issue by doraemonkeys** [filllabs/dependi#102]
Hello,

I've encountered an issue with the Dependi plugin when managing dependencies in my `go.mod` file. The plugin works correctly with the following format:

```go
module github.com/xxxx

go 1.22

toolchain go1.22.4

require (
    github.com/sirupsen/logrus v1.9.3
    golang.org/x/sys v0.21.0
)
```

However, when I use this format, the plugin does not seem to function properly:

```go
module github.com/xxxx

go 1.22

toolchain go1.22.4

require github.com/sirupsen/logrus v1.9.3

require golang.org/x/sys v0.21.0
```

**Desktop:**
 - OS: Windows 11
 - Version: 23H2
- dependi: v0.7.7

**Comment by MOzanGul** [comment]
Hi @doraemonkeys , we have fixed this issue in our newest version 0.7.8.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
