### ISSUE TITLE
[help] emoji/symbols aren't being displayed on vscode

### ISSUE THREAD

**Issue by lcdss** [filllabs/dependi#108]
I've tried a lot of font families and nothing seems to make the emojis to show on vscode. The current font family settings I'm using is: 'FiraCode Nerd Font', 'Noto Color Emoji', 'Symbols Nerd Font', 'Symbols Nerd Font Mono', 'Noto Sans Symbols', 'Noto Sans Symbols 2', 'PowerlineSymbols'.

![image](https://github.com/user-attachments/assets/74a11a06-aec0-4dae-bbcf-7071f8ad3e0b)

**Comment by MOzanGul** [comment]
Hi @lcdss , can you provide us your OS and computer specs?

**Comment by lcdss** [comment]
Sure @MOzanGul !

```
pc-remote-control/src-tauri on  master [✘!?] is 󰏗 v0.0.1 via 󱘗 v1.80.1
❯ neofetch
                     ./o.                  lcss@falcon
                   ./sssso-                -----------
                 `:osssssss+-              OS: EndeavourOS Linux x86_64
               `:+sssssssssso/.            Host: MS-7C94 1.0
             `-/ossssssssssssso/.          Kernel: 6.10.4-zen2-1-zen
           `-/+sssssssssssssssso+:`        Uptime: 4 days, 21 hours, 7 mins
         `-:/+sssssssssssssssssso+/.       Packages: 1228 (pacman), 37 (flatpak)
       `.://osssssssssssssssssssso++-      Shell: nu 0.96.1
      .://+ssssssssssssssssssssssso++:     Resolution: 2560x1440
    .:///ossssssssssssssssssssssssso++:    DE: GNOME 46.4
  `:////ssssssssssssssssssssssssssso+++.   WM: Mutter
`-////+ssssssssssssssssssssssssssso++++-   WM Theme: Adwaita
 `..-+oosssssssssssssssssssssssso+++++/`   Theme: adw-gtk3-dark [GTK2/3]
   ./++++++++++++++++++++++++++++++/:.     Icons: Adwaita [GTK2/3]
  `:::::::::::::::::::::::::------``       Terminal: WezTerm
                                           CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz
                                           GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/
                                           Memory: 23817MiB / 32021MiB
```
I checked my vscode and it's working now:

![image](https://github.com/user-attachments/assets/4e3eba40-9d6d-47eb-b968-c08e531d98b5)

I didn't restart the PC or did anything else but the vscode was restarted several times since then. Anyway, it's solved now.

**Comment by MOzanGul** [comment]
Hi @lcdss,
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
