### ISSUE TITLE
Allow disabling per lang

### ISSUE THREAD

**Issue by imranbarbhuiya** [filllabs/dependi#11]
**Is your feature request related to a problem? Please describe.**
I'm getting version check in package.json
**Describe the solution you'd like**
Hi, I want this deps only for rust and want to disable it for npm, Adding a new config which allows disabling it per lang will be really good
**Describe alternatives you've considered**
Go back to crate extension or stop using both
**Additional context**

**Comment by waynemaranga** [comment]
@imranbarbhuiya Another option you have is to [enable Dependi in a specific workspace](https://code.visualstudio.com/docs/editor/extension-marketplace#_enable-an-extension) and only that workspace, along with other extensions you use for Rust (rust-analyzer, BetterTOML) etc.

**Comment by serayuzgur** [comment]
Hi , @imranbarbhuiya  can you please describe why you need this? What are the benefits ?

**Comment by imranbarbhuiya** [comment]
> Hi , @imranbarbhuiya can you please describe why you need this? What are the benefits ?


I originally used crate extension for cargo.toml only and i dont need it in my package.json. So i would like to keep the old behavior and use it  this extension for rust only

**Comment by serayuzgur** [comment]
To clarify, are these features (versions, documentation, or vulnerabilities) necessary for package.json? 
While we can add these settings, it's best if people use Dependi for all their dependency needs.

**Comment by serayuzgur** [comment]
> > Hi , @imranbarbhuiya can you please describe why you need this? What are the benefits ?
> 
> I originally used crate extension for cargo.toml only and i dont need it in my package.json. So i would like to keep the old behavior and use it this extension for rust only

To clarify, are these features (versions, documentation, or vulnerabilities) necessary for package.json? 
While we can add these settings, it's best if people use Dependi for all their dependency needs.

**Comment by imranbarbhuiya** [comment]
> To clarify, are these features (versions, documentation, or vulnerabilities) necessary for package.json? 

for me or ovarral? for me I don't need it in package.json as my vscode already shows me docs link and latest version altho I don't use it from here, I just use `yarn upgrade-interactive` to do it. For vulnerabilities, github alerts and renovate/dependabot prs are enough for me
![image](https://github.com/user-attachments/assets/18c2cad5-690e-4f37-80d3-d435b8f0a364)

**Comment by serayuzgur** [comment]
> > To clarify, are these features (versions, documentation, or vulnerabilities) necessary for package.json?
> 
> for me or ovarral? for me I don't need it in package.json as my vscode already shows me docs link and latest version altho I don't use it from here, I just use `yarn upgrade-interactive` to do it. For vulnerabilities, github alerts and renovate/dependabot prs are enough for me ![image](https://private-user-images.githubusercontent.com/74945038/349407476-18c2cad5-690e-4f37-80d3-d435b8f0a364.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDI1OTQsIm5iZiI6MTcyMTIwMjI5NCwicGF0aCI6Ii83NDk0NTAzOC8zNDk0MDc0NzYtMThjMmNhZDUtNjkwZS00ZjM3LTgwZDMtZDQzNWI4ZjBhMzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA3NDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1M2Y1NWY1NjAyMDE5MTZjYWYwYzJiMTM3NGY2ZGQ5MTA3ZmQ5YTRjZWNiNTViZWY3MmZhYzgwM2FiZmVhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U2SqqdYBmyid6iwKZezGUyRPLCiq4WFVUmxUj2v_d14)
> 
> > While we can add these settings, it's best if people use Dependi for all their dependency needs.
> 
> Adding a way to opt-out will be a good feature imo

Thanks for the detailed reply , we will plan it. @MOzanGul 

As an additional question , which features can make you want to use with npm ? It will be a good feedback for future development.

**Comment by imranbarbhuiya** [comment]
> Thanks for the detailed reply , we will plan it. 

Thank you very much ♥️

> As an additional question , which features can make you want to use with npm ? It will be a good feedback for future development.

dependi seems to already provide a lot of cool features for developers. I personally don't open package.json much and do everything from package manager using cli. If I need any features that can be implemented in this extension, I'll share them in a new issue.

**Comment by imranbarbhuiya** [comment]
Thanks for the quick implementation ♥️

**Comment by MOzanGul** [comment]
Hi @imranbarbhuiya, we have added an option to disable dependi per language on our newer versions. You can disable Dependi per language from Extension Settings. 
We'd be really happy if you could review Dependi, here is our [marketplace page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
![image](https://github.com/user-attachments/assets/ec8dde32-3b94-4f42-b109-907f57a74f6c)

**Comment by imranbarbhuiya** [comment]
> Hi @imranbarbhuiya, we have added an option to disable dependi per language on our newer versions. You can disable Dependi per language from Extension Settings. We'd be really happy if you could review Dependi

Done, thanks for the implimentation
