### ISSUE TITLE
Please fix this issue

### ISSUE THREAD

**Issue by ssrlive** [filllabs/dependi#110]
![image](https://github.com/user-attachments/assets/b8be3a63-d2a7-405c-96bc-9ec88bc66976)

**Comment by MOzanGul** [comment]
Please provide us more information about this issue. You can see the template for bug reporting below.
https://github.com/filllabs/dependi/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ssrlive** [comment]
Emm, After running `cargo update`, this issue disappear. sorry.
