### ISSUE TITLE
No versions found ( ! ! ! ) for existing npm packages

### ISSUE THREAD

**Issue by ottosson** [filllabs/dependi#111]
**Describe the bug**
I'm getting a warning that no versions found for some dependencies. But they are installed without issues

**To Reproduce**
try adding xterm as a dependency

**Expected behavior**
I would expect dependi to display the green check mark in this case since the dependency exists

**Screenshots**
![image](https://github.com/user-attachments/assets/d9e86eb1-e03b-40d7-96b9-9a2baa24721a)

![image](https://github.com/user-attachments/assets/fe1cab6c-5345-4dd0-9635-2c2e81290840)

**Desktop (please complete the following information):**
 - OS: windows (haven't tried others)
 - Version: dependi 0.7.7

**Comment by RobertSobral** [comment]
I have some issues with RC versions not showing

![img](https://github.com/user-attachments/assets/61a6a839-71ee-47be-8432-ae70c139ed22)

OS: Windows using (VS Code)
Version: v0.7.8

**Comment by MOzanGul** [comment]
@RobertSobral, You're having this issue because Dependi excludes unstable versions of libraries as default, please go to your Extension Settings and uncheck the box below. Let us know if this has solved your problem.
![image](https://github.com/user-attachments/assets/8757c2d0-6e37-4ae1-9e60-49121205a63e)

**Comment by ottosson** [comment]
@MOzanGul Thanks, but it didn't help unfortunately.

> unstable versions

What does that mean? I wouldn't really call the latest version of Xterm unstable... 🤔

**Comment by MOzanGul** [comment]
@ottosson My comment was for @RobertSobral to fix his issue. I hope he can open a new issue if it still occurs.

About yours @ottosson we have seen that `xterm` npm package is deprecated in favor of another package. We will be improving the code to handle these situations better. Thanks for your patience!

**Comment by ottosson** [comment]
@MOzanGul Right! Sorry about the misunderstanding 🥸

Oh I didn't realize that! Would be great to add that info to the warning 😊 Thanks for letting me know!

**Comment by MOzanGul** [comment]
Hi @ottosson,
We have fixed this issue in our newest version 0.7.11.
Thank you for contributing!

**Comment by MOzanGul** [comment]
@ottosson 
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
