### ISSUE TITLE
Add support for `tool.uv.dev-dependencies` table in `uv`-managed Python projects

### ISSUE THREAD

**Issue by shunichironomura** [filllabs/dependi#116]
**Is your feature request related to a problem? Please describe.**
In the release of `v0.3.0`, [`uv`](https://docs.astral.sh/uv/) has [stabilized its capability to manage Python projects](https://astral.sh/blog/uv-unified-python-packaging), including the development dependencies. While the non-development dependencies specification follows the [PEP621](https://peps.python.org/pep-0621/), the development dependencies are specified using the dedicated [`tool.uv.dev-dependencies` field](https://docs.astral.sh/uv/reference/settings/#dev-dependencies) in the `pyproject.toml` file, which does not seem to be supported by dependi.

**Describe the solution you'd like**
Support the `tool.uv.dev-dependencies` table used in `uv`-managed Python projects.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MOzanGul** [comment]
@shunichironomura 
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
