### ISSUE TITLE
Dependency Versions Mask Cargo.toml Versions

### ISSUE THREAD

**Issue by BenD0G** [filllabs/dependi#117]
**Describe the bug**
Dependi will incorrectly mark outdated versions with a green tick, if a dependency contains an up-to-date version of the same crate. At time of writing, `rand` is on 0.8.5:
![image](https://github.com/user-attachments/assets/a7f6bfd0-43a6-4839-af6c-2d8c67a6d582)

**To Reproduce**
Make sure you have Lock File Enabled on.
Make a new crate, with this dependency section:
```toml
[dependencies]
proptest = "1.5"
rand = "0.1"
```
Dependi will mark `rand` with a tick. In the generated lock file, note that we have
```toml
[[package]]
name = "rand"
version = "0.1.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2d37d90a6118f2925173cb2b778aaabda804247d389cbff6f39fb558fddda113"
dependencies = [
 "libc 0.1.12",
 "log",
]

[[package]]
name = "rand"
version = "0.8.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "34af8d1a0e25924bc5b7c43c079c942339d8f0a8b57c39049bef581b46327404"
dependencies = [
 "libc 0.2.158",
 "rand_chacha",
 "rand_core",
]
```

**Expected behavior**
Dependi should warn that you have specified an outdated version in your TOML file.

**Screenshots**
![image](https://github.com/user-attachments/assets/a7f6bfd0-43a6-4839-af6c-2d8c67a6d582)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 24.04

**Additional context**
Possibly related to https://github.com/filllabs/dependi/issues/112.

**Comment by MOzanGul** [comment]
Hi @BenD0G , we have fixed this issue per your request in our new version.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
