### ISSUE TITLE
support npm package.json peerDependencies

### ISSUE THREAD

**Issue by ahaoboy** [filllabs/dependi#122]
**Describe the bug**
Dependencies in peerDependencies have no version information
Although the dependencies under this field do not need to be latest, it would be convenient if user could select the version.

![image](https://github.com/user-attachments/assets/31e53878-dc72-4410-b96a-82992086bdd3)

**Comment by MOzanGul** [comment]
Hi @ahaoboy , we have fixed this issue per your request in our new version.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
