### ISSUE TITLE
vscode language mode modified: json -> composer json

### ISSUE THREAD

**Issue by masterflitzer** [filllabs/dependi#127]
**Describe the bug**
the extension modifies the name of the built in "json" language mode from "json" to "composer json" and alters its search priority

**To Reproduce**
do this once with dependi extension enabled and once with it disabled:
1. create a new text file in vscode (file > new text file)
2. click on the "select language mode" button in the bottom right corner of the editor (should show "plain text" by default)
3. type "json"
4. See how the entry with "(json)" behind it says "composer json" when enabled and "json" when disabled and also how the order is different now as the modified name gets a lower priority

**Expected behavior**
the extension shouldn't modifiy the name of an existing language mode, especially when it alters the search priority

**Screenshots**
with dependi extension enabled
![image](https://github.com/user-attachments/assets/b1254995-91eb-4309-be9d-1d96968c63f6)
with dependi extension disabled
![image](https://github.com/user-attachments/assets/5990ad07-388a-4494-abab-2e2532dc1915)

**Versions**
 - OS: macos 14.6.1
 - vscode: 1.92.2
 - dependi: 0.7.8

**Comment by MOzanGul** [comment]
Hi @masterflitzer  , we have fixed this issue per your request in our 0.7.10 version.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
