### ISSUE TITLE
No versions load (both rust and pnpm)

### ISSUE THREAD

**Issue by lishaduck** [filllabs/dependi#130]
**Describe the bug**
It just gives !!! for everything, both latest and outdated.

**To Reproduce**
1. Open a manifest
2. It's all cluttered

**Expected behavior**
The functionality works.

**Screenshots**
<img width="199" alt="Screenshot 2024-09-05 at 10 10 39 AM" src="https://github.com/user-attachments/assets/e870714a-eab3-49c7-a1a9-9f4d7f9ba812">

<details><summary>Details</summary>
<p>

```console
Congratulations, your extension "dependi" is now active!
Updated version
v1/public/telemetries:POST 204-No Content
Error fetching versions for wrap-ansi: Error: statusCode=302:
... (lots more of the same error, but for other packages)
v1/public/telemetries:POST 204-No Content
v1/public/telemetries:POST 204-No Content
v1/public/telemetries:POST 204-No Content
``` 

</p>
</details> 

**Desktop (please complete the following information):**
 - OS: macOS
 - Version v0.7.8

**Additional context**
I am behind a firewall, but it's not one that's very restrictive.
Most things work (including all the other vscode extensions I use)

**Comment by kadirkaang** [comment]
Hi @lishaduck,

Thanks for the report! We couldn’t replicate the issue, but it might be firewall-related. Could you run these commands and share the output?

```
curl -I https://registry.npmjs.org/wrap-ansi
curl -I https://index.crates.io/se/rd/serde
```

Thanks!

**Comment by lishaduck** [comment]
```
HTTP/2 200 
date: Wed, 11 Sep 2024 12:19:19 GMT
content-type: application/json
cf-ray: 8c179afc1eb34de5-MCI
cf-cache-status: HIT
accept-ranges: bytes
access-control-allow-origin: *
age: 284
cache-control: public, max-age=300
etag: "096b0befe71ac4a3b08a6a2255515b73"
last-modified: Sat, 28 Oct 2023 17:40:35 GMT
vary: accept-encoding, accept
server: cloudflare
```

&

```
HTTP/2 200 
content-type: text/plain
content-length: 143070
last-modified: Fri, 06 Sep 2024 18:17:44 GMT
x-amz-server-side-encryption: AES256
x-amz-version-id: XCiqiF8qbG7aUYMzQTeXNyYFiknl4clQ
accept-ranges: bytes
server: AmazonS3
date: Wed, 11 Sep 2024 12:17:54 GMT
cache-control: public,max-age=600
etag: "1439e33ee097c1fdf71d61b9d343594d"
vary: Accept-Encoding
x-cache: Hit from cloudfront
via: 1.1 1297ec043592c7b1473e5982c5d90ea2.cloudfront.net (CloudFront)
x-amz-cf-pop: MCI50-P1
x-amz-cf-id: Q6uHEHz1wwHONeCiAylX3a7inLjWsJ_GBUHEi9ShCnY2LrvDTT5Q5w==
age: 92
```

**Comment by kadirkaang** [comment]
Hi @lishaduck,

Since the curl commands worked, could you check the Developer Tools console for errors? 
Here's how to open Developer Tools: 
![image](https://github.com/user-attachments/assets/8a9b973d-2cb5-4145-95ad-1e822f59c765)


Thanks!

**Comment by MOzanGul** [comment]
Hi @lishaduck  , we have fixed this issue per your request in our 0.7.10 version. Can you also check it if it is fixed for you?
Also we'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by lishaduck** [comment]
That fixed it, thanks!

**Comment by MaxKingPor** [comment]
@kadirkaang Same issue in `Ubuntu 24.04.1 LTS` with `Remote-SSH`
