### ISSUE TITLE
[npm]: support `latest` tag

### ISSUE THREAD

**Issue by RSS1102** [filllabs/dependi#131]
**Is your feature request related to a problem? Please describe.**

in `JavaScript`的package.json 
```json
// ...
packageName: "latest"；
```
use `npm i`，the latest version will be installed.

**Describe the solution you'd like**

It is detected like a normal package, except that its version is detected because it is already the latest version by default.

**Describe alternatives you've considered**

Or compare it with the version number that it thinks is the last version (but I think this is meaningless, it depends on the implementation of the original logic)

**Additional context**
<img width="398" alt="image" src="https://github.com/user-attachments/assets/05b41288-947d-43cd-88a3-373c1387a509">

<img width="650" alt="image" src="https://github.com/user-attachments/assets/10cefc9a-0bf9-40df-bf89-686644d669a7">

**Comment by MOzanGul** [comment]
Hi @RSS1102 , we have fixed this issue per your request in our new version.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by RSS1102** [comment]
My pleasure, the bug was fixed very quickly and I am very happy, the community is active.
