### ISSUE TITLE
Remove the update notification

### ISSUE THREAD

**Issue by GRA0007** [filllabs/dependi#138]
Currently this extension shows a notification every time it's updated. This is unnecessary and annoying — no other extensions I have do this.

Please remove the update notification; if I want to read the changelog I can go to the extension's page and click the changelog tab.

**Comment by Possseidon** [comment]
I 100% agree with everything @GRA0007 said. Please remove it or at least add a setting for it as you mentioned.

**Comment by MOzanGul** [comment]
Hi @Possseidon @GRA0007 ,
We have added an option to the settings where you can silence update notifications. Thank you for contributing!
![image](https://github.com/user-attachments/assets/4bbcf641-80be-4089-bcfc-ca3977afb541)

We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
