### ISSUE TITLE
Missing or malformed JWT

### ISSUE THREAD

**Issue by danny-su** [filllabs/dependi#14]
**Screenshots**
<img width="487" alt="image" src="https://github.com/user-attachments/assets/eaac142d-9b3b-4fdb-8121-b3a9738b01e4">

**Desktop (please complete the following information):**
OS: macOS 14.5
Dependi: v0.7.1

**Additional context**

**Comment by serayuzgur** [comment]
Hi @danny-su  thanks for reaching. Did you entered your api key ?

**Comment by danny-su** [comment]
@serayuzgur Yes, I used my API key.

**Comment by serayuzgur** [comment]
We will contact you via mail to understand your case. Thanks

**Comment by MOzanGul** [comment]
This issue has been solved. Thank you for contributing.
