### ISSUE TITLE
npm wrong field stackblitz in package.json

### ISSUE THREAD

**Issue by ahaoboy** [filllabs/dependi#143]
**Describe the bug**
![image](https://github.com/user-attachments/assets/e18f60e3-ab07-4b2e-a39d-aa85a0a2ea72)

**To Reproduce**
```json
"stackblitz": {
  "startCommand": "npm run bench:ui"
},
```

**Expected behavior**
This field should be excluded.

**Comment by MOzanGul** [comment]
Hi @ahaoboy   ,
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
