### ISSUE TITLE
Support pnpm workspace and catalog version specifiers

### ISSUE THREAD

**Issue by TheOnlyTails** [filllabs/dependi#149]
Dependi currently does not recognize pnpm's `workspace:` and `catalog:` version specifiers.
- `workspace:` refers pnpm to another package within the same workspace
- `catalog:` uses a version defined in the `pnpm-workspace.yaml` file, such that it can be shared between packages in the same workspace.

Dependi should be able to recognize and understand both of these.

**Comment by MOzanGul** [comment]
Hello @TheOnlyTails,
Thank you for reporting this issue with Dependi!
We’ll review and update you soon.

**Comment by MOzanGul** [comment]
Hi @TheOnlyTails ,
We have added the support for pnpm workspace and catalog version specifiers per your request in our new version.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
