### ISSUE TITLE
some rust index mirror need to trailing slash

### ISSUE THREAD

**Issue by EXHades** [filllabs/dependi#151]
some rust index server mirror sites need trailing slash to working

```jsonc
{
  "dependi.rust.indexServerURL": "https://rsproxy.cn/index/",
  // "dependi.rust.indexServerURL": "https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"
}
```

current configuration will prompt an alarm：

```
String does not match the pattern of "^https?://(?!.*//)([^/]+/)*[^/]+$".
```

**Comment by MOzanGul** [comment]
Hi @EXHades, we are putting the slash while we are sending requests to the index server as default. That's why it will decorate it as an error. We suggest you to not type a trailing slash as we do it in code.

**Comment by EXHades** [comment]
Thanks, I got it。

**Comment by MOzanGul** [comment]
Hi @EXHades  ,
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
