### ISSUE TITLE
Doesn't handle `||` operator (in npm)

### ISSUE THREAD

**Issue by lishaduck** [filllabs/dependi#152]
**Describe the bug**
You can support multiple majors, at least in npm, using the `||` operator

**To Reproduce**
1. Create a project supporting multiple major versions of a dependency.
2. Scroll to the location of the dependency in the manifest.
3. See outdated warning

**Expected behavior**
It should understand that it supports the latest version.

**Screenshots**
<img width="399" alt="Screenshot 2024-09-23 at 10 16 18 AM" src="https://github.com/user-attachments/assets/8baf48a2-ba99-4e4d-b183-fc31704b4285">

**Desktop (please complete the following information):**
- OS: macOS
- Version v0.7.8

**Additional context**
Thanks for fixing #130! Other than this, it works like a charm!

**Comment by MOzanGul** [comment]
Hi @lishaduck, we think that this issue might be because the lock file parsing is on. When it is on we consider the value as locked.  Can you please turn it off and check if the issue still persists?
