### ISSUE TITLE
Explain why there are exclamation marks by my dependency

### ISSUE THREAD

**Issue by JohnstonJ** [filllabs/dependi#156]
**Is your feature request related to a problem? Please describe.**

Dependi is showing exclamation marks by my dependency in Rust, and I don't know why:

![image](https://github.com/user-attachments/assets/bf3a2406-a220-42e6-a2ff-241fed3504a3)

If I hover the mouse over this exclamation mark icon, I just get this popup-up listing the versions.

What do the red exclamation marks mean?  Seems like this should be:

- Explained in the pop-up (along with explanations of other icons when they appear as well)
- And/or documented somewhere.  The [documentation](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi) on the marketplace page doesn't explain.  I can't find any documentation at all on the [homepage](https://www.dependi.io/), either.

**Describe the solution you'd like**

Make it simple and intuitive to understand what the various symbols and icons shown by Dependi actually mean.  Don't assume users know what an icon means, because they probably don't.

**Describe alternatives you've considered**

Digging through source code of Dependi to find out the conditions of when some exclamation marks are shown.  I don't have time to dig through Dependi source code of the extension.  This should be clearly explained.

**Additional context**
See above screenshot.

**Comment by MOzanGul** [comment]
Hello @JohnstonJ  ,
Thank you for reporting this issue with Dependi! We are planning to add documents section to our [Landing Page](https://dependi.io/).
We’ll review and update you soon.

**Comment by MOzanGul** [comment]
Hi @JohnstonJ, 
We fixed this issue on our newest version 0.7.11. 
Thank you for contributing!

**Comment by MOzanGul** [comment]
@JohnstonJ 
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
