### ISSUE TITLE
add installed extensions to README

### ISSUE THREAD

**Issue by andrewgazelka** [filllabs/dependi#158]
**Describe.**

https://github.com/filllabs/dependi has a beautiful screenshot

![image](https://github.com/user-attachments/assets/176bc737-be67-44f3-a5dd-66cd2b441978)

It would be nice to know which extensions are being used (i.e., file icon themes)

**Describe the solution you'd like**
Include extensions in screenshot caption

**Comment by serayuzgur** [comment]
Hi ,
It was for screenshots and changed long time ago. Sorry I don't remember.
