### ISSUE TITLE
Is $17.88 the price per year or per month?

### ISSUE THREAD

**Issue by danny-su** [filllabs/dependi#16]
Is $17.88 the price per year or per month?

Home page(https://www.dependi.io/#pricing):
<img width="419" alt="Arc 2024-07-17 14 36 28" src="https://github.com/user-attachments/assets/8c08994f-990c-48ca-b1d7-9caa8c067213">

Payment page(https://www.dependi.io/pro/payment):
<img width="506" alt="Arc 2024-07-17 14 36 47" src="https://github.com/user-attachments/assets/d6134b9d-2031-4a69-b4f7-0e4093aaed8b">

**Comment by serayuzgur** [comment]
It's per year. Sorry for the confusion; we're working on fixing that bug.
