### ISSUE TITLE
Incorrect version failures with python

### ISSUE THREAD

**Issue by emilyselwood** [filllabs/dependi#161]
**Describe the bug**
Dependencies showing with red crosses when it looks like they shouldn't

**To Reproduce**
1. Have a python poetry project
2. have a dependency on `html5lib = "^1.1"` or `wget = "^3.2"`
3. See markers next to the dependencies with red crosses and the same version listed as the newest version. See screen shots below

**Expected behavior**
I'd expect to see green ticks next to the dependencies as currently they are the latest version.

**Screenshots**
<img width="260" alt="Screenshot 2024-10-11 at 13 23 07" src="https://github.com/user-attachments/assets/979d88c3-767f-4374-87c0-076baae15062">
<img width="280" alt="Screenshot 2024-10-11 at 13 23 35" src="https://github.com/user-attachments/assets/2cb90502-6b93-4c23-b3d3-9891903b66c9">

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Version 15.0.1

**Additional context**
Looking through our dependency list it looks like the ones its failing on are the ones with two digit version numbers rather than 3 digit versions.

**Comment by MOzanGul** [comment]
Hello @emilyselwood ,
Thank you for reporting this issue with Dependi!
We’ll review and update you soon.

**Comment by alanwilter** [comment]
I have the same issue with several packages, e.g.:
<img width="507" alt="Screenshot 2024-10-30 at 11 28 55" src="https://github.com/user-attachments/assets/94a81c2a-ad2e-4e8f-96e4-f0c801a07512">
And `poetry show| grep 'opencv-python-headless' clearly shows:
```
opencv-python-headless   4.10.0.84         Wrapper package for OpenCV pytho...
```

**Comment by MOzanGul** [comment]
Hi @JohnstonJ and @alanwilter , 
We fixed this issue on our newest version 0.7.11. 
Thank you for contributing!

**Comment by alanwilter** [comment]
Brilliant! Just checked, all fine here. Thanks a lot.

**Comment by MOzanGul** [comment]
@emilyselwood @alanwilter 
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
