### ISSUE TITLE
Alternative names are not detected for `requirements.txt`

### ISSUE THREAD

**Issue by tylerlaprade** [filllabs/dependi#162]
**Describe the bug**
The extension only detects my `requirements.txt`, not `requirements-dev.txt`

**To Reproduce**
1. Create `requirements-dev.txt`
2. Put some dependencies in it

**Expected behavior**
The extension should show me whether my dev dependencies are up to date

**Screenshots**
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/651eae1a-2607-4d3a-ad82-cef9f6a7a507">
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/e58e7d99-819a-43c9-b114-9381e8b8b395">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Sonoma 14.6.2

**Comment by MOzanGul** [comment]
Hello @tylerlaprade  ,
Thank you for reporting this issue with Dependi!
We’ll review and update you soon.

**Comment by MOzanGul** [comment]
Hi @tylerlaprade , 
We fixed this issue on our newest version 0.7.11. 
Thank you for contributing!

**Comment by MOzanGul** [comment]
@tylerlaprade 
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by tylerlaprade** [comment]
Thanks but this isn't the only relevant name. In my project we also have `requirements-prod.txt` and `requirements-bootstrap.txt`. Other projects might have different names. Is a more generalized solution possible?

**Comment by MOzanGul** [comment]
@tylerlaprade Sorry about that. We will reopen this issue and try to implement a more generalized solution.
Thank you for your comment.

**Comment by fefe982** [comment]
to work with [pip-tools](https://pypi.org/project/pip-tools/), now I have a "requirements.in", which is also in the format of requirements.txt.

**Comment by MOzanGul** [comment]
> to work with [pip-tools](https://pypi.org/project/pip-tools/), now I have a "requirements.in", which is also in the format of requirements.txt.
Hi @fefe982, we have opened an issue for your request and will work on it.

**Comment by MOzanGul** [comment]
Hi @tylerlaprade,
We have implemented a more generalized solution for this issue in our new version 0.7.12. Thank you for contributing!
Let us know if you have any feedbacks.

We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by tylerlaprade** [comment]
This seems better, thanks
