### ISSUE TITLE
Empty string as decoration template goes back to default

### ISSUE THREAD

**Issue by Strikeless** [filllabs/dependi#163]
**Describe the bug**
If you explicitly set any of the decoration templates to an empty string "" in the preferences, the decoration doesn't change from the default. I wish and would expect this to work as it did in crates, so that the decoration becomes invisible as per the empty string.

**To Reproduce**
1. Go to your VSCode preferences
2. Set any of the decoration templates to an empty string (dependi.decoration.compatible.template for example)
3. See the decoration in Cargo.toml for example

**Expected behavior**
I would expect the decoration to become invisible as per the empty string.

**Screenshots**
![image](https://github.com/user-attachments/assets/80dc9221-0086-420f-8611-091b5823c43d)
![image](https://github.com/user-attachments/assets/f82336b2-eaea-48b5-af0c-5d56b47beb0e)

**Desktop (please complete the following information):**
 - OS: Arch
 - Visual Studio Code version: 1.94.2
 - Dependi version: v0.7.10

**Additional context**
The expected behavior can currently be achieved with a string that has a single space " ", but to me this is non-obvious and counter-intuitive.

**Comment by MOzanGul** [comment]
Hello @Strikeless  ,
Thank you for reporting this issue with Dependi!
We’ll review and update you soon.

**Comment by MOzanGul** [comment]
Hi @Strikeless , 
We fixed this issue on our newest version 0.7.11. 
Thank you for contributing!
