### ISSUE TITLE
Shows "no versions found" for unclear reasons on `project.requires-python`

### ISSUE THREAD

**Issue by rspeer** [filllabs/dependi#164]
**Describe the bug**

Dependi puts three red exclamation points next to the line `requires-python = ">=3.9"` in [my pyproject.toml](https://github.com/rspeer/python-ftfy/blob/main/pyproject.toml).

If I mouse over it, it says `Error: requires-python: No versions found.`

**To Reproduce**

* Install dependi in VS Code.
* Check out the [python-ftfy](https://github.com/rspeer/python-ftfy) repository.
* Create a virtual environment with the package installed in it, in the `.venv` directory.
* Activate `.venv/bin/python` as the current Python interpreter in VS Code.
* Open the repository as a VS Code project.
* Open `pyproject.toml` in VS Code.

My virtualenv is currently built on Python 3.12.3.

**Expected behavior**

There should not be an error on the `requires-python` line. That is the standard and correct way to configure the minimum version of Python a project needs.

**Desktop (please complete the following information):**

 - OS: Ubuntu 24.04

**Additional context**

Is it possible that dependi thinks that this line is in the `project.dependencies` section, and that it should be looking for a Python package named "requires-python"? That's not what the line means. It's in the top-level `project` section and it's about the version of Python that needs to be installed.

**Comment by MOzanGul** [comment]
Hi @rspeer  , 
We fixed this issue on our newest version 0.7.11. 
Thank you for contributing!

**Comment by MOzanGul** [comment]
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
