### ISSUE TITLE
Cargo: Doesn't Correctly Highlight Version Being Too High

### ISSUE THREAD

**Issue by BenD0G** [filllabs/dependi#171]
**Describe the bug**
In `Cargo.toml`, if you set `actix = "1.0"` or `tokio = "1000"`, dependi will show a green tick (pictured below).

**To Reproduce**
1. Make a new cargo project
2. In `Cargo.toml`, add a dependency with a higher version number than exists.

**Expected behavior**
Should show a warning sign instead of a tick, to let you know that you've asked for an incorrect version.

**Screenshots**
![image](https://github.com/user-attachments/assets/7fbc89d2-df44-4daa-8f2f-6d0cb13bfee2)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 24.04

Thanks!

**Comment by MOzanGul** [comment]
Hello @BenD0G  ,
Thank you for reporting this issue with Dependi!
We’ll review and update you soon.

**Comment by MOzanGul** [comment]
Hi @BenD0G,
Upon further review, we want to share you why you are experiencing this issue.

While fixing the issue #1, we have changed the way Dependi acts when the registry doesn't send us the latest versions of packages. In this case we have removed the upper limit of package versions.

We would be really happy if you have any ideas on how Dependi should act regarding this information.

Thanks in advance for your comments.

**Comment by JulianGmp** [comment]
To add my two cents here, I would suggest showing an error to the user in this case.
For example, selecting `log = "1.0"` leads to Dependi giving you a green check, but when you try to build the project cargo will rightfully error out with
> error: failed to select a version for the requirement `log = "^1.0"`
> candidate versions found which didn't match: 0.4.22, 0.4.21, 0.4.20, ...
> location searched: crates.io index

**Comment by MOzanGul** [comment]
Hi @BenD0G @JulianGmp,
We have added an option to the settings where you can silence the overflow versions. By checking the box you can solve this issue. 
![image](https://github.com/user-attachments/assets/357c7cd8-3b18-48b0-a198-f6f2f50e6a69)

We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
