### ISSUE TITLE
Empty "Welcome to Dependi" tab opens every time I open vscode

### ISSUE THREAD

**Issue by zjeffer** [filllabs/dependi#175]
**Describe the bug**
Every time I open a rust project in vscode, the "Welcome to Dependi" page opens. The page is empty.
The output log of the Dependi extension only says:

```
Congratulations, your extension "dependi" is now active!
First install
```

**To Reproduce**
1. Open vscode
2. Go to File > Open File > open a cargo.toml file.
3. The "Welcome to Dependi" page will open and will be empty

or: 

1. Open vscode
2. Go to File > Open Folder > Choose a rust project's folder that contains a cargo.toml file.
3. The "Welcome to Dependi" page will open and will be empty

**Expected behavior**
1. The welcome page should only open when the extension is first installed.
2. The page should not be empty (I assume)

**Screenshots**
![image](https://github.com/user-attachments/assets/141080b8-a9cb-441e-950c-26416518336e)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - vscode version `1.95.1` (from the `visual-studio-code-bin` arch package)
 - Extension version `v0.7.11`

**Additional context**
/

**Comment by advorkovyy** [comment]
Same here

**Comment by advorkovyy** [comment]
Found workaround:

```shell
touch /home/$USER/.vscode-server/extensions/fill-labs.dependi-0.7.11/CHANGELOG.md
```

Worked for me

**Comment by joshmackwilliams** [comment]
Same problem here. I found that the changelog is downloaded as "changelog.md", but the extension tries to open "CHANGELOG.md". I just renamed the file and it works now.

**Comment by zjeffer** [comment]
That workaround works for me too! Thanks @advorkovyy & @joshmackwilliams

I wonder why it's downloaded as "changelog.md"? Or should the file it expects be lowercase, so it matches the file it downloads?
Also, why does this problem suddenly appear now? If I look at the history, the file in the repo has always been uppercase. I assume this was tested and worked at some point, so what could have caused it to break?

**Comment by 951mmm** [comment]
awesome

**Comment by jpenna** [comment]
> Dependi writes in output every time it starts: "Congratulations, your extension "dependi" is now active! First install"
> 
> And I see an error in the log message:
> 
> ```
> 2024-11-07 08:00:58.723 [error] Error: ENOENT: no such file or directory, open '/home/username/.vscode-server/extensions/fill-labs.dependi-0.7.11/CHANGELOG.md'
>     at readFileSync (node:fs:448:20)
>     at to (/home/username/.vscode-server/extensions/fill-labs.dependi-0.7.11/out/main.js:37:600)
>     at t._getWelcomePageHtml (/home/username/.vscode-server/extensions/fill-labs.dependi-0.7.11/out/main.js:69:372)
>     at t.getWebviewContent (/home/username/.vscode-server/extensions/fill-labs.dependi-0.7.11/out/main.js:69:169)
>     at new t (/home/username/.vscode-server/extensions/fill-labs.dependi-0.7.11/out/main.js:69:115)
>     at Function.render (/home/username/.vscode-server/extensions/fill-labs.dependi-0.7.11/out/main.js:69:306)
>     at pu (/home/username/.vscode-server/extensions/fill-labs.dependi-0.7.11/out/main.js:69:4733)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

For those wondering where to find these logs and error message:

Dependi logs: Output > Dependi
Error log: Output > Extension Host > (search for the Error)

In the error you also find the path you should use to create the CHANGELOG.md

**Comment by scarf005** [comment]
@MOzanGul there aren't any linked PR or commit to fixes, could we get the link?

**Comment by MOzanGul** [comment]
Hi@scarf005,
Here is the related PR.
https://github.com/filllabs/dependi/pull/184
