### ISSUE TITLE
Support for pixi.toml

### ISSUE THREAD

**Issue by jjjermiah** [filllabs/dependi#179]
**Is your feature request related to a problem? Please describe.**
[pixi is a package manager](pixi.sh) for the conda ecosystem + python, 

**Describe the solution you'd like**
Additional support for `pixi.toml` and the conda packages 

**Describe alternatives you've considered**
whereas I could only use the pyproject.toml, it does not always apply if im not working with pure python

willing to help out here wherever I can, including answering any questions!

**Comment by MOzanGul** [comment]
Hello @jjjermiah  ,
Thank you for reporting this issue with Dependi!
We’ll review and update you soon.

**Comment by MOzanGul** [comment]
Hi @jjjermiah ,
We have added support to the pixi.toml files in our newest version 0.7.13. Thank you for contributing!

We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
