### ISSUE TITLE
[Python] Support PEP 735 – Dependency groups in `pyproject.toml`

### ISSUE THREAD

**Issue by shunichironomura** [filllabs/dependi#182]
**Is your feature request related to a problem? Please describe.**

[PEP 735 – Dependency Groups in pyproject.toml](https://peps.python.org/pep-0735/) defines the standard way to specify dependency groups in Python, and [was accepted on 2024-10-10](https://discuss.python.org/t/pep-735-dependency-groups-in-pyproject-toml/39233/312).

So in case of managing dependencies with `uv`, for example, the old way of specifying dependency groups using [the `dev-dependencies` field](https://docs.astral.sh/uv/reference/settings/#dev-dependencies) is no longer recommended.

**Describe the solution you'd like**
Support PEP 735-style dependency groups definition in `pyproject.toml`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MOzanGul** [comment]
Hi @shunichironomura,
We have added support for the PEP 735 in our latest version 0.7.13. Thank you for contributing!

We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
