### ISSUE TITLE
Green checkmark displayed when not appropriate

### ISSUE THREAD

**Issue by smoelius** [filllabs/dependi#185]
**Describe the bug**
When using Dependi with Cargo, I frequently see a green checkmark displayed when it should not be.

Specifically, this occurs when I enter `1.0` for the version, but the dependency's latest version is `0.x`.

**To Reproduce**
1. Run `cargo new a`.
2. Open `a/Cargo.toml`.
3. Add `toml = "1.0"` under the `[dependencies]` section.

**Expected behavior**
A red `X` or some other ligature.

**Screenshots**
<img width="372" alt="dependi" src="https://github.com/user-attachments/assets/37716087-faa0-4990-914c-18480ddcbe54">

**Desktop (please complete the following information):**
 - OS: Linux/macOS
 - Version 0.7.11

**Comment by MOzanGul** [comment]
Hi @smoelius ,
We have added an option to the settings where you can silence the overflow versions. By checking the box you can solve this issue. 
![image](https://github.com/user-attachments/assets/357c7cd8-3b18-48b0-a198-f6f2f50e6a69)

We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by smoelius** [comment]
> Hi @smoelius , We have added an option to the settings where you can silence the overflow versions. By checking the box you can solve this issue.

Thanks a ton!

> We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

I'm having trouble creating Microsoft account, but I'll try again shortly.

Thanks again!
