### ISSUE TITLE
random rude question

### ISSUE THREAD

**Issue by Mon-ius** [filllabs/dependi#20]
I have to warn people who install this extension that will make u entire vscode dev env f**k up

**Comment by serayuzgur** [comment]
Thanks for your comment, but it's not very helpful. Could you specify exactly what problems you're facing with the extension? It's important to provide constructive feedback rather than just being rude.

**Comment by Mon-ius** [comment]
Yeah, in order to publish your `Dependi Pro`, enforce the stable `erates` becoming disabled, then force user to use your new product then hacking their dev environment, what a graceful operation 🤗

**Comment by Mon-ius** [comment]
I tested five profile, which shows that after remove `Dependi` then install back `Crates` then remove `Crates`, everything recover back, not sure which dirty operation were performed, we dont have enough time for debugging the opened code, as we all know, the VSC itself's binary is not compiled from the opened code. `Crates` works perfect, and surely `Dependi` is stronger enough to easily break our weak dev profile setup 🤗

**Comment by serayuzgur** [comment]
I see you, but your attitude isn't helpful. You can either open a well-described issue to help us debug the problem and be productive, or you can resort to hate speech and try to outsmart the developers who provided this extension for free with more features. You've chosen the second option, which only creates conflict and serves no one but the hate culture itself. You're always welcome to use the old Crates or open a new issue to help us make Dependi bug-free. Choose wisely.

**Comment by Mon-ius** [comment]
No blame, we already seen many of cases in recent years, change name and do evil things 🤗
