### ISSUE TITLE
Python update checks don't work with Artifactory as python index server url

### ISSUE THREAD

**Issue by mattmess1221** [filllabs/dependi#22]
Trying to use an Artifactory PyPi mirror creates a 404 error message. This is because Artifactory does not implement the `/pypi/<package>/json` endpoint.

Using [PEP 691](https://peps.python.org/pep-0691/) would be more correct, but unfortunately Artifactory only supports the HTML API.

**Comment by serayuzgur** [comment]
@killjoy1221  can you please share a test url from Artifactory

**Comment by killjoy1221** [comment]
Unfortunately the artifactory I use is internal and not accessible to the internet. But you should be able to get a trial instance from jfrog.

**Comment by serayuzgur** [comment]
> Unfortunately the artifactory I use is internal and not accessible to the internet. But you should be able to get a trial instance from jfrog.

Hi, it seems integrating with Artifactory is quite a pain. The API isn't designed for scenarios like this, so we are closing this issue. If you find a good way to connect via the API, please share it with us.

**Comment by camball** [comment]
Just want to +1 here and show support, I may be able to look into it one day if I get some time.
