### ISSUE TITLE
Silently fails when requirements.txt contains non-package lines

### ISSUE THREAD

**Issue by killjoy1221** [filllabs/dependi#23]
requirements.txt files containing paths (`./foo`) or pip options (`--index-url`) will silently fail.

Example requirements.txt:
```
annotated-types==0.7.0
anyio==4.4.0
asyncstdlib==3.12.4
certifi==2024.7.4
click==8.1.7
colorama==0.4.6; platform_system == "Windows"
fastapi==0.110.3
h11==0.14.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
idna==3.7
pydantic==2.8.2
pydantic-core==2.20.1
pydantic-settings==2.3.4
python-dotenv==1.0.1
sniffio==1.3.1
starlette==0.37.2
typing-extensions==4.12.2
uvicorn==0.30.1
uvloop==0.19.0
xlsxwriter==3.2.0
.  # this package
--index-url https://pypi.org/simple/
```

This file will fail to parse. No error is shown.

**Comment by serayuzgur** [comment]
@killjoy1221  until we fix it you can place `# dependi: disable-check` to the line

**Comment by MOzanGul** [comment]
Hi @killjoy1221  , we have fixed this issue on our newer versions per your request.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
