### ISSUE TITLE
Dependi doesn't support globbing in Rust

### ISSUE THREAD

**Issue by donottellmetonottellyou** [filllabs/dependi#24]
**Describe the bug**
Dependi does not recognize [`x.x.*` version requirement syntax](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#wildcard-requirements), despite showing in the versions popup that the latest version is selected. If told to update versions, it changes `x.x.*` to `x.x.x*` which is incorrect.

**To Reproduce**
1. Specify for example `strum = "0.26.*"`.
2. Observe the ❗❗❗.
3. Run `Dependi: Update All dependencies to the latest version` from the command pallet.
4. Observe the ✅.
5. Notice that rust-analyzer extension has crashed, and the following error occurs when running cargo build:
```
Caused by:
  failed to parse the version requirement `0.26.3*` for dependency `strum`

Caused by:
  expected comma after patch version number, found '*'
```

**Expected behavior**
I expect that Dependi would explicitly state that it doesn't support globbing using a notification, automatically remove globs for caret requirements, or leave them alone and only update them when a minor version update is required. This also goes for any other version syntax it doesn't currently support.

It is my opinion that `x.x.x` is less intuitive than `x.x.*`, since `x.x.x` actually will be automatically updated behind the scenes to the latest `x.x.*`.

**Screenshots**
![image](https://github.com/user-attachments/assets/84c206c2-9595-48a9-8911-ab6e4893a82a)

**Desktop (please complete the following information):**
 - OS: NixOS Linux
 - Version 24.05

**Additional context**
I am using NixOS's method to install extensions rather than installing directly from the marketplace. In addition, the extensions are in a read-only directory.

**Comment by MOzanGul** [comment]
@donottellmetonottellyou, are you still experiencing this issue? We couldn't reproduce this bug in our tests.

**Comment by donottellmetonottellyou** [comment]
@MOzanGul 

The latest version (0.7.8) does appear to correctly identify the version, and has an appropriate default of setting to a numeric version when running `Dependi: Update All dependencies to the latest version`.

A new issue is that in certain circumstances, it will display a green check next to invalid versions, e.g. `godot = "0.0.1"`, which is not a real available version. This should probably be its own issue though.
