### ISSUE TITLE
Dependi sends multiple leading slashes to npm, causing an error when Artifactory is npm index

### ISSUE THREAD

**Issue by killjoy1221** [filllabs/dependi#25]
Dependi is sending multiple leading slashes in the npm url, as seen here.

https://github.com/filllabs/dependi/blob/8357b7488f0c501bb16a6c9b03844f0fcdb9f84f/vscode/src/api/index/npm-index-server.ts#L20

Unfortunately, artifactory doesn't automatically strip these duplicate slashes, so it responds with 404.

```
@vueuse/core: Error: statusCode=404: npm.example.com//@vueuse/core
```

**Comment by killjoy1221** [comment]
#17 will fix this

**Comment by MOzanGul** [comment]
Hi @andrewbrey , we have fixed this issue on our newer versions per your request.
We'd be really happy if you could review Dependi, here is our [marketplace page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
