### ISSUE TITLE
Allow users to disable languages in favour of their respective dependency extensions

### ISSUE THREAD

**Issue by d3rpp** [filllabs/dependi#28]
**Is your feature request related to a problem? Please describe.**

I'm working on a large PNPM workspace (along side my rust-based projects) at my current Company, and since installing Dependi, every time I've tinkered with the `package.json` files it has failed to look up an *internal* dependency of the workspace on npm (specified with `workspace:*`) since well, it doesn't exist on npm.

**Describe the solution you'd like**

As a precursor to adding support for other JS Package Managers or just in general, would it be a good idea to make it possible to simply disable support for a language and allow a languages current implementation to continue as is?

I have no problem using this extension in place of the `crates` extension (assuming this is added), though it is a bit frustrating that the extension insists on taking over the extensions of other languages while not being feature compatible with the current standard extensions. 

**Describe alternatives you've considered**

I've returned to a fork of crates in the meantime so it won't leak into my other languages in the projects.

**Additional context**

There's no issue with unifying these systems and I think it's overall a very good idea, but not having the ability to disable things to ensure a smooth transition (especially in a team project) is throwing a spanner in the works to say the least.

Happy to discuss further :D

**Comment by serayuzgur** [comment]
I think you are right.  We also have an issue about [this](https://github.com/filllabs/dependi/issues/11)
we will put additional settings for disabling

**Comment by MOzanGul** [comment]
Hi @d3rpp , we have added an option to disable dependi per language on our newer versions. You can disable Dependi per language from Extension Settings. 
We'd be really happy if you could review Dependi, here is our [marketplace page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
![image](https://github.com/user-attachments/assets/ec8dde32-3b94-4f42-b109-907f57a74f6c)

**Comment by d3rpp** [comment]
Hi @MOzanGul,

Thanks for this change, it's made using dependi in my rust projects very epic whilst allowing projects that don't fully work with it to be worked on properly.

I'll use it at work for a bit to ensure I get a proper amount of experience before writing up a review, it seems like a very helpful setup.

Thanks :D
