### ISSUE TITLE
Bug while fetching info for Rust workspace libraries

### ISSUE THREAD

**Issue by gnapoli23** [filllabs/dependi#29]
**Describe the bug**
I have a project made up of several local libraries/binaries managed in a workspace, and Dependi tries to fetch info about these local crates from `index.crates.io` causing an obvious `404` error.

**To Reproduce**
1. Create a Rust project with a workspace, with 2 or more members
2. Open the main `Cargo.toml` file, Dependi will start fetching metadata from `index.crates.io`, showing the `404` error for the local libs

**Expected behavior**
Dependi should differ from local to public/published crates

**Screenshots**
![dep_error](https://github.com/user-attachments/assets/d8e87705-81a0-4c9f-a650-057b1ddfc76a)

**Desktop (please complete the following information):**
 - OS: `debian`
 - Version `bookworm`

**Comment by serayuzgur** [comment]
Hi @gnapoli23, thanks for reaching out. You are right, it's a bug. @MOzanGul, let's plan this.

**Comment by MOzanGul** [comment]
Hi @gnapoli23, we have fixed this issue per your request.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
