### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by ziimakc** [filllabs/dependi#39]
Where can I see extension logs to debug an error?
![image](https://github.com/user-attachments/assets/ceabb5db-3ef5-46de-bb1b-a85154bf90c9)

**Comment by serayuzgur** [comment]
You can use Developer Mode right now. We are working on output tab logs
<img width="478" alt="image" src="https://github.com/user-attachments/assets/169e498d-5969-487c-8eec-c2b2a3dba03f">

**Comment by ziimakc** [comment]
It doesn't show any errors, just infinite spinner :(
