### ISSUE TITLE
When typing into commit message, depenency for cargo.toml is reloaded with each input change

### ISSUE THREAD

**Issue by izderadicka** [filllabs/dependi#4]
**Describe the bug**
When I type to commit message with each change in the input active Cargo.toml window always reloads dependency.

**To Reproduce**
1. Open project Cargo.toml file
2. Open Source Control
3. Type into commit message
4. With each change in input dependencies in Cargo.toml are reloaded -  toaster appears - Fetching dependecy information

**Expected behavior**

**Screenshots**
See attached screencast 
[Screencast from 4.7.2024 14:02:22.webm](https://github.com/filllabs/dependi/assets/2185733/784b387d-9a49-4555-aebe-e3e1af104c68)

**Desktop (please complete the following information):**
 - OS:  Ubuntu
 - Version : 20.04
 - Dependi : 0.7.0
 - VS Code: 1.90.2

**Comment by MOzanGul** [comment]
Hi @izderadicka, we have fixed this issue on our newer versions.
We'd be really happy if you could review Dependi, here is our [marketplace page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
