### ISSUE TITLE
Make it possible to remove the "Welcome to Dependi" page

### ISSUE THREAD

**Issue by dollannn** [filllabs/dependi#43]
**Is your feature request related to a problem? Please describe.**
Extremely frustrating having the welcome page open after every update. I understand you want to promote the PRO tier but this is beyond frustrating. I despise an extension opening stuff without my consent, especially when its not just a changelog.

**Describe the solution you'd like**
Option to disable the page opening.

**Describe alternatives you've considered**
Uninstalling the extension

**Additional context**

**Comment by serayuzgur** [comment]
Please check at 0.7.4

**Comment by MOzanGul** [comment]
Hi @dollannn  , we have fixed this issue on 0.7.4 version per your request.
We'd be really happy if you could review Dependi, here is our [marketplace page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by Frtzqe** [comment]
I am using version 0.7.11, and experience the opening of an new file "Welcome to Dependi" (new and empty). 

So, is this the same thing as pre 0.7.4?
