### ISSUE TITLE
Avoid dependency on "Even Better TOML"

### ISSUE THREAD

**Issue by djc** [filllabs/dependi#48]
**Describe the bug**

I've gotten confused about why Dependi wasn't working for me, and it turned out to be because I had Even Better TOML installed but disabled. It's not obvious to me why Dependi needs to depend on Even Better TOML, but I don't like it:

1. Even Better TOML is fairly opinionated about formatting TOML in a way that I often don't like
2. As I understand it, Even Better TOML itself is deprecated in favor of an Even Betterer TOML extension

Please reconsider this dependency.

**Comment by serayuzgur** [comment]
Hi @djc,
Thanks for raising the issue. Do you think we should rely on Even Betterer TOML for this, or should we implement TOML language detection ourselves?

**Comment by serayuzgur** [comment]
> What problem is the TOML language detection solving for you? Why not just work with any file with `.toml` extension?

You are right. Previously, some people reported that Dependi wasn't working without the TOML extension installed, but it seems that is no longer the case. Thanks for figuring that out.

**Comment by MOzanGul** [comment]
Hi @djc   , we have fixed this issue per your request.
We'd be really happy if you could review Dependi, here is our [marketplace page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
