### ISSUE TITLE
Vulnerability notifications in Cargo manifests are too eager

### ISSUE THREAD

**Issue by djc** [filllabs/dependi#51]
**Describe the bug**

In my application, I version both the `Cargo.toml` file (which is normal) and the `Cargo.lock` file. Versioning the lockfile has always been recommended for applications but recently(ish) the Cargo team also started recommending this for libraries. Dependi currently shows an alarm light in `Cargo.toml` if the lower bound for a dependency has RUSTSEC issues. However, IMO it should not do so unless the related `Cargo.lock` file actually has a version that is old enough to be vulnerable. I prefer to not bump the lower bound in my `Cargo.toml` for this since that mostly creates unnecessary churn.

I guess a workaround would be to just remove the decoration for vulnerable versions but IMO it would be nicer if Dependi gets this right from the start (although I see how there's some additional complexity from dealing with the separate lockfile).

**To Reproduce**

1. `Cargo.toml` has `tokio = { version = "1.1.1" }`, `Cargo.lock` has tokio at 1.38.1
2. Dependi shows 3 vulnerabilities

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 0.7.4

**Comment by MOzanGul** [comment]
Hi @djc, we have added support to .lock files in our newest version 0.7.8. If a .lock file is existing in the project we will be checking the versions and decorating the manifest files according to the versions in .lock files. You can disable this in the Extension settings any time.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by djc** [comment]
1. As you can see in the OP, this issue was filed against 0.7.4 which did not support the lockfile checking.
2. With 0.7.8 even though I have `"dependi.rust.lockFileEnabled": false`, I still see the vulnerability alert decoration.

IMO the current implementation around matching the manifest and lockfile data is too simplistic.
