### ISSUE TITLE
^workspace should be ignored by default

### ISSUE THREAD

**Issue by ahaoboy** [filllabs/dependi#52]
**Describe the bug**
Installing local dependencies will prompt an error
Some local protocols should be ignored by default, since they are the latest , such as file://xxx and ^workspace

**To Reproduce**
```
"@mpv-easy/tool": "workspace:*",
```

**Expected behavior**
 No error message

![image](https://github.com/user-attachments/assets/4044323d-5b65-4325-a286-45eda7829a6f)

**Comment by MOzanGul** [comment]
Hi @ahaoboy  , we have fixed this issue per your request. From now on, Dependi will not show errors for local workspaces.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
