### ISSUE TITLE
Fail to order pre-release versions for Python dependencies

### ISSUE THREAD

**Issue by shunichironomura** [filllabs/dependi#58]
**Describe the bug**
The extension displays ❌ with the pre-release version next to the newer stable version.

**To Reproduce**
1. Prepare a `requirements.txt` with the following content:
```
typer==0.12.3
datashader==0.16.3
```

2. Open the file in VS Code with the extension. The extension displays `❌ 0.12.dev2` for `typer` and `❌ 0.16.3rc0` for `datashader`. The extension settings are all set to defaults.

**Expected behavior**
The extension shows `✅` for both cases, as they are the latest stable versions. Also, I want "0.12.dev2" to be regarded as older than "0.12.3" and "0.16.3rc0" older than "0.16.3".

The [Semantic Versioning](https://semver.org/) requires a hyphen between the version core and pre-release, and I'm guessing that may be the cause of this. But it seems to be the standard in Python. See [Version specifiers - Python Packaging User Guide](https://packaging.python.org/en/latest/specifications/version-specifiers/#pre-releases).

**Screenshots**
![image](https://github.com/user-attachments/assets/04017465-cd4b-473f-837b-ee59f4315636)

**Desktop (please complete the following information):**
 - OS: Linux (WSL2 Ubuntu)
 - Version: v0.7.5

**Comment by JP-Ellis** [comment]
As a whole, pre-releases should probably _not_ be recommended at all. Most Python tools require to explicitly opt-in to pre-releases when dependencies are installed.

**Comment by serayuzgur** [comment]
> As a whole, pre-releases should probably _not_ be recommended at all. Most Python tools require to explicitly opt-in to pre-releases when dependencies are installed.

Thanks for the info. We defined a setting for that , means they are excluded by default but if you insist  yo see them.

**Comment by serayuzgur** [comment]
@shunichironomura  does this works for you ?
<img width="376" alt="image" src="https://github.com/user-attachments/assets/919edfa3-1baa-47df-a70d-4c2948e76ca7">

**Comment by shunichironomura** [comment]
@serayuzgur Yes, that's what I expect to see.

**Comment by JP-Ellis** [comment]
I still have an instance where a pre-release is being shown:

<img width="293" alt="image" src="https://github.com/user-attachments/assets/b4d65454-f737-4836-8cf7-7ead298163d8">

Not sure whether that is an edge case due to the `~=0.0` selection.

**Comment by serayuzgur** [comment]
> I still have an instance where a pre-release is being shown:
> 
> <img alt="image" width="293" src="https://private-user-images.githubusercontent.com/3196162/352343277-b4d65454-f737-4836-8cf7-7ead298163d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODg3MDQsIm5iZiI6MTcyMTk4ODQwNCwicGF0aCI6Ii8zMTk2MTYyLzM1MjM0MzI3Ny1iNGQ2NTQ1NC1mNzM3LTQ4MzYtOGNmNy03ZWFkMjk4MTYzZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMTAwNjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE0NmEyZGI5NWNhYWQ5OWQ5OWIxNjJkYWYzNDhmMTAwYjA1ZWU4OWFhODcyZTU3NjlkMDAyOTMyZWMxYTFmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3SbHn6Wrp6NJf-W74S5vn4Eb2nj0B5W6OzLpEP5k6RE">
> Not sure whether that is an edge case due to the `~=0.0` selection.

This will fix it

**Comment by MOzanGul** [comment]
Hi @shunichironomura  , we have fixed this issue per your request. 
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
