### ISSUE TITLE
[Rust] Version information not displayed for wildcard version

### ISSUE THREAD

**Issue by JoshLambda** [filllabs/dependi#59]
**Describe the bug**
In Rust file `Cargo.toml`, when hovering wildcard version with mouse cursor, the expected tooltip containing version information isn't displayed at all.
_Exemple:  hovering the `*` of `dotenvy = "*"`, the tooltip with version information doesn't appear._
(It's is still being displayed normally if version is a number.)

**To Reproduce**
See above.

**Expected behavior**
Version information is expected to be displayed.

**Screenshots**
(none)

**Desktop (please complete the following information):**
Windows 10
Visual Studio 1.91.1

**Additional context**
Dependi v0.7.5 (current)

**Comment by MOzanGul** [comment]
Hi @JoshLambda   , we have fixed this issue per your request.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
