### ISSUE TITLE
[Python] Fails for the `skyfield` package

### ISSUE THREAD

**Issue by shunichironomura** [filllabs/dependi#60]
**Describe the bug**
The VS Code extension shows ❌ for `skyfield==1.49`, even though it is the latest version.

**To Reproduce**

1. Create a `requirements.txt` file with the following content:

```
skyfield==1.49
```

2. Open it in VS Code with the extension.
3. The extension displays `❌ 1.49`

**Expected behavior**
The extension displays ✅ 

**Screenshots**
![image](https://github.com/user-attachments/assets/6cc80823-74b9-4aa0-bd6b-3fa8bcd078db)

**Desktop (please complete the following information):**
 - OS: Linux (WSL2 Ubuntu 22.04)
 - Version: v0.7.5

**Comment by serayuzgur** [comment]
Hi @shunichironomura  
Thanks for reaching us. We are adding it to the development plan. It will be fixed at next version.

**Comment by MOzanGul** [comment]
Hi @shunichironomura , we have fixed this issue per your request.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
