### ISSUE TITLE
`pyproject.toml` Incorrect `~=0.0` matching

### ISSUE THREAD

**Issue by JP-Ellis** [filllabs/dependi#66]
There is inconsistent behaviour when checking for `~=0.0` vs non-zero versions:

<img width="288" alt="image" src="https://github.com/user-attachments/assets/f0550706-d23d-4e70-9969-7bf30a89a7bb">

For Python, [PEP 440](https://peps.python.org/pep-0440/#compatible-release) makes it very clear that `~=x.y` is equivalent to `>=x.y, ==x.*`; and furthermore has no exception when `x` or `y` is 0. Similarly, `~=x.y.z` is equivalent to `>=x.y.z, ==x.y.*`.

The above example indicates that the latest version of Pytest is selected (which is correct), but would suggest that `pytest-asyncio` is behind (which is incorrect).

EDIT: I would like to highlight that this behaviour is subtly different from [node-semver's tilde ranges](https://github.com/npm/node-semver?tab=readme-ov-file#tilde-ranges-123-12-1).

**Comment by MOzanGul** [comment]
Hi @JP-Ellis  , we have fixed this issue per your request.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
