### ISSUE TITLE
Does this include contributed code from Crates?

### ISSUE THREAD

**Issue by trevyn** [filllabs/dependi#7]
Hi Seray,

Crates (https://github.com/serayuzgur/crates) was an MIT-licensed project with 21 contributors. Is Dependi a new project from scratch, or does it contain contributed, MIT-licensed code?

**Comment by serayuzgur** [comment]
Hi, 
Dependi is written from scratch.  Since I wrote most of the both projects they may have similar approaches but  it is planned, featured and coded from zero. I hope it answers what you asked.
