### ISSUE TITLE
[Rust] Alert not displayed when minor version is outdated

### ISSUE THREAD

**Issue by JoshLambda** [filllabs/dependi#74]
**Describe the bug**
```
[dependencies]
uuid = "1.4" 
```
Last version is 1.10.0, but no alert is displayed (green mark is shown).

**To Reproduce**
See above.

**Expected behavior**
Expected behavior: alert shown (red icon) for minor version (X.Y) number mismatch.

**Screenshots**
Minor version mismatch isn't detected as shown on screenshot below:
<img width="207" alt="dependi" src="https://github.com/user-attachments/assets/af2ea328-99ac-4988-ab4f-1c7b399d4ac2">

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Visual Studio Code v1.91.1 (current)
Dependi v0.7.5 (current)

**Comment by JoshLambda** [comment]
Problem still happening with Dependi v0.7.7

**Comment by MOzanGul** [comment]
Hi @JoshLambda, if you'd like to get notified for the minor updates you need to declare your dependencies using tilde.
e.g. `uuid = "~1.4" `
![image](https://github.com/user-attachments/assets/8ee01dd0-1b44-43f0-bd25-83a601d68126) 
You can check the official Cargo documentation here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by JoshLambda** [comment]
Thanks!

**Comment by MOzanGul** [comment]
Hi @JoshLambda,
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
