### ISSUE TITLE
Dependi - Extension - Python - Error in some libraries

### ISSUE THREAD

**Issue by MOzanGul** [filllabs/dependi#77]
Error decaorator comes when a library has pre-release version in the version list.
ex for pyproject.toml:
`"moto-ext[all]>=3.1.14`

![Image](https://github.com/user-attachments/assets/36124b60-fed4-4892-83a5-64360bc6144f)

ex for req.txt: 
`django>=55.1b1`

![Image](https://github.com/user-attachments/assets/2d7aae3a-2aff-4505-89d9-3ebc1d422ca0)

**Comment by JonathanPlasse** [comment]
This also error.
![image](https://github.com/user-attachments/assets/1becc44c-5608-48f6-8199-b6ec3e62b7ea)
