### ISSUE TITLE
Python - requirements.txt does not support dependencies with feature

### ISSUE THREAD

**Issue by KagurazakaNyaa** [filllabs/dependi#91]
https://github.com/filllabs/dependi/blob/494ebb5219595eeb757f764b9bb1ad591d7d5de2/vscode/src/core/parsers/PypiParser.ts#L37 should add "["

![image](https://github.com/user-attachments/assets/9a815fd3-e5ca-47ac-8053-85889efcb564)

example:
```requirements.txt
fastapi[all]>=0.111.0,<1  # this line report error
apscheduler>=3.10,<4
motor>=3.3,<4
redis>=5.0,<5.1
python-jose>=3.3,<4
```

**Comment by MOzanGul** [comment]
Hi @KagurazakaNyaa, we have fixed this issue per your request in our new version 0.7.7.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by MOzanGul** [comment]
Hi @KagurazakaNyaa, we have fixed this issue per your request in our new version 0.7.7.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
