### ISSUE TITLE
Add support for local npm registries using http protocol

### ISSUE THREAD

**Issue by gepz** [filllabs/dependi#93]
**Is your feature request related to a problem? Please describe.**
Dependi currently does not support the "http:" protocol, which prevents integration with local npm registries like Verdaccio. This limitation hinders developers who use private or local registries for dependency management.

**Describe the solution you'd like**
Implement support for the "http:" protocol in Dependi, allowing users to connect to local npm registries. This would enable seamless integration with tools like Verdaccio and other private registry solutions that may not use HTTPS.

**Describe alternatives you've considered**
- Using HTTPS for local registries (not always feasible or desired)
- Manually managing dependencies outside of Dependi for projects using local registries

**Additional context**
None

**Comment by MOzanGul** [comment]
Hi @gepz,

First of all sorry for the delay. Can you check if this issue still persists? We think we fixed this on our newest version 0.7.13. We tested and it was working fine.

Waiting for your feedbacks.

**Comment by MOzanGul** [comment]
We're happy to hear that. 
We'd also be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by MOzanGul** [comment]
@gepz We're happy to hear that. 
We'd also be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).
